version: "3.8"

services:
  ddns-receiver:
    build: .
    container_name: ddns-receiver
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8000"
    restart: unless-stopped
    environment:
      - CF_ZONE_ID=your_zone_id
      - CF_TOKEN=your_token
      - DDNS_USER=office_admin
      - DDNS_PASS=secret_pass
